/**
 * Demo Hreflang Output
 * 
 * Shows what the actual hreflang tags look like in HTML
 */

import { generateHreflangLinks } from '../lib/geo/hreflang';

console.log('📄 Hreflang HTML Output Demo\n');
console.log('This shows what the hreflang tags look like in the HTML <head>\n');
console.log('='.repeat(70));

const examples = [
  { path: '', name: 'Home Page' },
  { path: 'blog', name: 'Blog List' },
  { path: 'blog/web3-security-trends-2025', name: 'Blog Article' },
  { path: 'products/exchange', name: 'Exchange Product' },
];

examples.forEach(({ path, name }) => {
  console.log(`\n${name} (${path || '/'})`);
  console.log('-'.repeat(70));
  
  const links = generateHreflangLinks({ path });
  
  links.forEach(({ hreflang, href }) => {
    console.log(`<link rel="alternate" hreflang="${hreflang}" href="${href}" />`);
  });
});

console.log('\n' + '='.repeat(70));
console.log('\n✨ These tags are automatically generated by Next.js metadata API');
console.log('   and included in the <head> of each page.\n');
