/**
 * Test Hreflang Metadata Generation
 * 
 * This script tests that the actual metadata generated by pages
 * includes proper hreflang alternates.
 */

import { generateHreflangAlternates, generateCanonicalUrl } from '../lib/geo/hreflang';

interface TestCase {
  locale: string;
  path: string;
  description: string;
}

const testCases: TestCase[] = [
  { locale: 'zh', path: '', description: 'Chinese Home Page' },
  { locale: 'en', path: '', description: 'English Home Page' },
  { locale: 'zh', path: 'blog', description: 'Chinese Blog List' },
  { locale: 'en', path: 'blog', description: 'English Blog List' },
  { locale: 'zh', path: 'blog/web3-security-trends-2025', description: 'Chinese Blog Article' },
  { locale: 'en', path: 'blog/web3-security-trends-2025', description: 'English Blog Article' },
  { locale: 'zh', path: 'products/exchange', description: 'Chinese Exchange Page' },
  { locale: 'en', path: 'products/exchange', description: 'English Exchange Page' },
];

function testMetadataGeneration() {
  console.log('🧪 Testing hreflang metadata generation...\n');
  
  let allPassed = true;
  
  testCases.forEach(({ locale, path, description }) => {
    console.log(`Testing: ${description}`);
    
    // Generate canonical URL
    const canonical = generateCanonicalUrl(locale, path);
    console.log(`  Canonical: ${canonical}`);
    
    // Generate hreflang alternates
    const alternates = generateHreflangAlternates({ path });
    
    // Verify canonical URL format
    const expectedCanonical = `https://develop.matrixlab.work/${locale}${path ? `/${path}` : ''}`;
    if (canonical !== expectedCanonical) {
      console.log(`  ❌ Canonical URL mismatch!`);
      console.log(`     Expected: ${expectedCanonical}`);
      console.log(`     Got: ${canonical}`);
      allPassed = false;
    } else {
      console.log(`  ✅ Canonical URL correct`);
    }
    
    // Verify alternates
    console.log(`  Alternates:`);
    Object.entries(alternates).forEach(([lang, url]) => {
      console.log(`    ${lang}: ${url}`);
    });
    
    // Check required alternates
    const requiredLangs = ['zh-CN', 'en-US', 'x-default'];
    requiredLangs.forEach(lang => {
      if (!alternates[lang]) {
        console.log(`  ❌ Missing ${lang} alternate`);
        allPassed = false;
      }
    });
    
    // Verify x-default points to Chinese version (default locale)
    const expectedDefault = `https://develop.matrixlab.work/zh${path ? `/${path}` : ''}`;
    if (alternates['x-default'] !== expectedDefault) {
      console.log(`  ❌ x-default doesn't point to default locale`);
      console.log(`     Expected: ${expectedDefault}`);
      console.log(`     Got: ${alternates['x-default']}`);
      allPassed = false;
    } else {
      console.log(`  ✅ x-default points to default locale`);
    }
    
    console.log('');
  });
  
  if (allPassed) {
    console.log('✨ All metadata generation tests passed!');
    return 0;
  } else {
    console.log('❌ Some tests failed. Please review the output above.');
    return 1;
  }
}

const exitCode = testMetadataGeneration();
process.exit(exitCode);
